version: '3'

services:
  web:
    build: ./
    working_dir: /code/bakerydemo
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./wagtail:/code/wagtail:delegated,rw
      - ./bakerydemo:/code/bakerydemo:delegated,rw
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://wagtail:changeme@postgres/wagtail
      PYTHONPATH: /code/wagtail:/code/bakerydemo:$PYTHONPATH
    depends_on:
      - db
      - frontend
  db:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_DB: wagtail
      POSTGRES_PASSWORD: changeme
    restart: always
    expose:
      - "5432"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    working_dir: /code/wagtail
    volumes:
      - ./wagtail:/code/wagtail:delegated,rw
    command: npm run start
